name: tools
description: A simple command-line application.
# version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: '>=2.10.0 <3.0.0'

dependencies:
  csv: ^4.1.0
  intl: ^0.17.0
  pub_api_client: ^1.0.9
  tabulate: ^0.0.1

dev_dependencies:
  pedantic: ^1.9.0
